// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/proto/person.proto

//指定最后生成的.pb.go文件的包名

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_HOME   Person_PhoneType = 0
	Person_WORK   Person_PhoneType = 101
	Person_MOBILE Person_PhoneType = 102
)

var Person_PhoneType_name = map[int32]string{
	0:   "HOME",
	101: "WORK",
	102: "MOBILE",
}

var Person_PhoneType_value = map[string]int32{
	"HOME":   0,
	"WORK":   101,
	"MOBILE": 102,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_844c5b352b0d63cf, []int{0, 0}
}

//使用message定义Person结构体，按照上面的类型映射一一映射
type Person struct {
	No                   string                `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  int32                 `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"`
	Address              []string              `protobuf:"bytes,6,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c5b352b0d63cf, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c5b352b0d63cf, []int{0, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_HOME
}

func init() {
	proto.RegisterEnum("proto.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Person)(nil), "proto.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "proto.Person.PhoneNumber")
}

func init() { proto.RegisterFile("helloworld/proto/person.proto", fileDescriptor_844c5b352b0d63cf) }

var fileDescriptor_844c5b352b0d63cf = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xed, 0xbf, 0x68, 0xcf, 0x60, 0x94, 0x73, 0xa1, 0x51, 0x10, 0xca, 0xae, 0x0a, 0x83,
	0x0e, 0xe7, 0x1b, 0x08, 0x03, 0x45, 0x67, 0x47, 0x10, 0xbc, 0xee, 0xe8, 0xd1, 0x5d, 0x74, 0x49,
	0x48, 0x26, 0xae, 0x2f, 0xe3, 0xb3, 0x4a, 0x4f, 0xab, 0x78, 0xe1, 0x55, 0x7e, 0xdf, 0x2f, 0x27,
	0xf9, 0x0e, 0x5c, 0xef, 0xa8, 0x6d, 0xcd, 0xa7, 0x71, 0x6d, 0xb3, 0xb0, 0xce, 0x1c, 0xcc, 0xc2,
	0x92, 0xf3, 0x46, 0x97, 0x1c, 0x30, 0xe1, 0x63, 0xf6, 0x15, 0x82, 0xd8, 0xb0, 0xc7, 0x29, 0x84,
	0xda, 0xc8, 0x20, 0x0f, 0x8a, 0x54, 0x85, 0xda, 0x20, 0x42, 0xac, 0xeb, 0x3d, 0xc9, 0x90, 0x0d,
	0x33, 0x66, 0x10, 0xd5, 0xef, 0x24, 0xa3, 0x3c, 0x28, 0x12, 0xd5, 0x63, 0x6f, 0x3c, 0x1d, 0x65,
	0x3c, 0x18, 0x4f, 0x47, 0xbc, 0x01, 0x61, 0x77, 0x46, 0x93, 0x97, 0x49, 0x1e, 0x15, 0x93, 0xe5,
	0xe5, 0xd0, 0x58, 0x0e, 0x35, 0xe5, 0xa6, 0xbf, 0x7b, 0xfe, 0xd8, 0x6f, 0xc9, 0xa9, 0x71, 0x10,
	0x25, 0x9c, 0xd6, 0x4d, 0xe3, 0xc8, 0x7b, 0x29, 0xf2, 0xa8, 0x48, 0xd5, 0x4f, 0xbc, 0x52, 0x30,
	0xf9, 0xf3, 0x00, 0xcf, 0x41, 0x68, 0xa6, 0x71, 0xcf, 0x31, 0xe1, 0x1c, 0xe2, 0x43, 0x67, 0x87,
	0x5d, 0xa7, 0xcb, 0x8b, 0x7f, 0x1a, 0x5f, 0x3a, 0x4b, 0x8a, 0x87, 0x66, 0x73, 0x48, 0x7f, 0x15,
	0x9e, 0x41, 0x7c, 0x5f, 0xad, 0x57, 0xd9, 0x49, 0x4f, 0xaf, 0x95, 0x7a, 0xcc, 0x08, 0x01, 0xc4,
	0xba, 0xba, 0x7b, 0x78, 0x5a, 0x65, 0x6f, 0x5b, 0xc1, 0x5f, 0xdd, 0x7e, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x96, 0xbe, 0x3c, 0xf2, 0x4f, 0x01, 0x00, 0x00,
}
